name: Bump Version, Create Tag, and Cache

on:
  push:
    branches: [master]

jobs:
  run:
    name: "Bump version, create pre-release and cache"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      # Setup and build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --silent --frozen-lockfile
      - name: Build
        run: yarn build

      # Semantics release
      # Update changelog
      # Update package.json
      # Create GH tag
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      # Get new release tag
      - name: Get tag
        id: get-tag
        run: echo "RELEASE_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      # # Yarn pack and upload .tgz
      # - run: yarn pack
      # - name: Cache tgz
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/*.tgz
      #     key: ${{ env.RELEASE_TAG }}-package

      # Upload Dist
      - name: Cache Dist
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: ${{ env.RELEASE_TAG }}-dist
