name: Publishing NPM

run-name: Publishing ${{ github.event.inputs.releaseTag }}

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Tag of version to be published to NPM"
        required: true

jobs:
  publish:
    name: "Publish to GitHub Packages and NPM"
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      # Update Release
      - name: Create Pre-release
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              await github.rest.repos.updateRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: process.env.RELEASE_TAG,
                prerelease: false,
                make_lateststring: true
              });
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.RELEASE_TAG }}-package
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@digitalspace"
      - run: echo "registry=https://npm.pkg.github.com/@digitalspace" >> .npmrc
      - run: yarn publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
