name: Publishing NPM

run-name: Publishing ${{ github.event.inputs.releaseTag }} to prod

on:
  release:
    types: [published]

jobs:
  publish:
    if: github.event_name == 'release' && github.event.action == 'published'
    name: "Publish to GitHub Packages and NPM"
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.RELEASE_TAG }}-package
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
          scope: "@digitalspace"
      - run: echo "registry=https://npm.pkg.github.com/@digitalspace" >> .npmrc
      - run: yarn publish $(ls *.tgz)
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
